### ISSUE TITLE
Docs is misleading for  using a prebuilt Docker image

### ISSUE THREAD

**Issue by thibaultleouay** [tursodatabase/libsql#1011]
https://github.com/tursodatabase/libsql/blob/main/docs/BUILD-RUN.md#using-a-prebuilt-docker-image

In the text it's written 
```The URL is https://ghcr.io/libsql/sqld.``` 
but in the example bellow 
```ghcr.io/tursodatabase/libsql-server:latest```

**Comment by LucioFranco** [comment]
thanks https://github.com/tursodatabase/libsql/pull/1013 fixed here!
