### ISSUE TITLE
Suggestion: an official Python library

### ISSUE THREAD

**Issue by simonw** [tursodatabase/libsql#117]
Most people who use SQLite with Python today do so via the `sqlite3` module in the Python standard library.

This is powerful and convenient, but it has some serious limitations. Most notably, it's extremely difficult to control or upgrade the version of SQLite that is provided by this library.

I made some notes on one way to do this using `LDD_PRELOAD` here: https://til.simonwillison.net/sqlite/ld-preload

Another way of addressing this is to use `pysqlite3` by Charles Leifer: https://github.com/coleifer/pysqlite3

This is a really great option - and even includes a `pysqlite3-binary` wheel that can be installed directly on Linux, skipping the need to build it from scratch.

There's still room for improvement though, and it strikes me that `libsql` may be in a position to take advantage of this need.

Imagine if there was an official package for the latest`libsql` release available on PyPI - with binary wheels for every platform, so any Python user could `pip install libsql` and then start using it:

```python
import libsql

db = libsql.connect("my.db")
...
```
This could start out as a direct port if the existing `sqlite3` package, similar to `pysqlite3`. But it could then become a place for shipping new features, no longer tied to the release cycle of the Python standard library:

- custom table-valued functions
- WASM extension support
- and so much more

Setting this all up would not be trivial... but I think it could help make libsql available to a very large she receptive new audience.

**Comment by Abdur-rahmaanJ** [comment]
I approve of this as libSQL has been undergoing rapid change cycles, which cannot be sustained even if at one point libSQL is included in the standard library.

@simonw are you on the discord? Me too i would like to help!

**Comment by psarna** [comment]
That's a great idea. It would be even better if libSQL support could be added as an opt-in feature to one of the existing packages. On the other hand, I see that `pysqlite3` is already dynamically linked to `libsqlite3.so` library, so it's enough to just install libSQL in one of the system paths, and `pysqlite3` should work out of the box with it. That said, having a Python package that always gets shipped with statically linked newest stable release of libSQL would be neat.

There's also value in adding libSQL-specific API on top, e.g. hooks for virtual WAL and helper functions related to WebAssembly user-defined functions. I'm not an expert in the Python environment, so I'd appreciate any help :)

**Comment by simonw** [comment]
> it's enough to just install libSQL in one of the system paths, and pysqlite3 should work out of the box with it

I've been finding it _extremely_ hard to figure out how to "install libSQL in one of the system paths" across the various operating systems I care about!

**Comment by psarna** [comment]
Ref: https://github.com/libsql/sqld/pull/148

**Comment by yozlet** [comment]
@simonw I stopped by and noticed there's now https://github.com/libsql/libsql-client-py - is that good enough to close this?

**Comment by penberg** [comment]
There is https://github.com/libsql/libsql-client-py that is compatible with the Python SQLite module so I am closing this.
