### ISSUE TITLE
No runtime available error 

### ISSUE THREAD

**Issue by tekjar** [tursodatabase/libsql#1350]
I'm constructing tokio runtime myself to make certain async methods synchronous in my code. I'm hitting this error when I switch from local to remote.

https://github.com/tursodatabase/libsql/blob/508274d9a68851fa468dfb5f555f7aecb815563a/libsql/src/hrana/hyper.rs#L91

Any option to fix this without using a global runtime?

**Comment by tekjar** [comment]
Closing in favour of #806

**Comment by kai2008** [comment]
I encountered the same issue. WARN libsql::hrana::hyper: Attempted to send a request to https://db-user.aws-us-region-1.turso.io/v3/pipeline, but no runtime was available.”
