### ISSUE TITLE
[C Bindings] missing column type enum

### ISSUE THREAD

**Issue by ospfranco** [tursodatabase/libsql#1412]
When using the [C experimental bindings](https://github.com/tursodatabase/libsql/blob/main/bindings/c/include/libsql.h#L95) I'm missing the enum for the mapping of the int to the column type. I'm guessing they match the sqlite3 types but since they are not in the headers I would have to go spelunking to map them.

Can you add the enum to the types? a #[repr(C)] ([link](https://doc.rust-lang.org/nomicon/other-reprs.html)) should be used in case they come from Rust code.

**Comment by ospfranco** [comment]
I just took a look into the [sqlite docs](https://www.sqlite.org/c3ref/c_blob.html), and they are pre-processor macros. Patched my code for now with:

```C++
#define LIBSQL_INT = 1
#define LIBSQL_FLOAT = 2
#define LIBSQL_TEXT = 3
#define LIBSQL_BLOB = 4
#define LIBSQL_NULL = 5
```

**Comment by haaawk** [comment]
It does not seem that we could expose the enum directly as the order of values there is different than the numbers they map to. We could define LIBSQL_INT, LIBSQL_FLOAT, .... and  so on.
