### ISSUE TITLE
[C Bindings] open remote connection fails with CA certificates on Android

### ISSUE THREAD

**Issue by ospfranco** [tursodatabase/libsql#1432]
I seem to have hit this issue:

https://github.com/rustls/hyper-rustls/issues/187

Here a user tried to connect to a turso remote database on Android:

https://github.com/OP-Engineering/op-sqlite/issues/102#event-12993539677

The proposed solution is using a different API which has been made available only on Rust:

https://github.com/tursodatabase/libsql/issues/789

On rust the `open_remote_with_connector` function has been exposed, which does not use root certificates but webpki. I guess I would also need the same function exposed to the C bindings.

**Comment by haaawk** [comment]
This is what you have to do to get this working on Android:

```
```

**Comment by haaawk** [comment]
I guess I could expose a new C function just for Android that would do the above internally.

**Comment by ospfranco** [comment]
awesome. thanks!
