### ISSUE TITLE
No such function: vector

### ISSUE THREAD

**Issue by filipjnc** [tursodatabase/libsql#1495]
According to [this post](https://turso.tech/blog/turso-brings-native-vector-search-to-sqlite), libsql should have native support for vectors. However, when I try to insert a vector like described in the post via libsql client I get `LibsqlError: SQLITE_ERROR: no such function: vector`. Any advice?

Version: `"@libsql/client": "^0.6.2"`

**Comment by lojik-ng** [comment]
I am facing the same issue with Typescript. Were you able to find a solution?

**Comment by filipjnc** [comment]
@haaawk I didn't create it on turso but locally. Does this command apply locally as well?

**Comment by haaawk** [comment]
> @haaawk I didn't create it on turso but locally. Does this command apply locally as well?

Not at the moment.

**Comment by penberg** [comment]
The `vector()` function is now part of the Rust, JavaScript, and Python SDKs.
