### ISSUE TITLE
Error while creating index for vector database table

### ISSUE THREAD

**Issue by aradhya-tiwari** [tursodatabase/libsql#1550]
I am trying to create a vector store using following command:- 

```
CREATE TABLE IF NOT EXISTS
  embeddings (
    text TEXT,
    metadata TEXT,
    embedding F32_BLOB (1536)
  );

CREATE INDEX IF NOT EXISTS documents_idx ON documents (
  libsql_vector_idx (embedding, 'type=diskann', 'metric=cosine')
);
```

and getting this error

> Error: SQLITE_UNKNOWN: SQLite error: unexpected vector column type: F32_BLOB (1536)
    at window.drizzle (https://turso.tech/_next/static/chunks/7061-c994b6446462fd0a.js:1:28549)
    at async Object.raw (https://turso.tech/_next/static/chunks/74f8cf84.b675ca02858c4173.js:400:7686)
    at async Object.raw (https://turso.tech/_next/static/chunks/74f8cf84.b675ca02858c4173.js:400:3481)
    at async executeSqlQuery (https://turso.tech/_next/static/chunks/74f8cf84.b675ca02858c4173.js:258:19680)

I have updated my default group version to vector using 
> turso group create default --version vector

I also found that when I execute turso db show <My Database Name> the version is **ector** instead of **vector**

**Comment by sivukhin** [comment]
Hi @aradhya-tiwari!

I think the error is due to space between `F32_BLOB` type name and dimension arguments. Can you try DDL like this:
```
CREATE TABLE IF NOT EXISTS
  embeddings (
    text TEXT,
    metadata TEXT,
    embedding F32_BLOB(1536)
  );
```

About `ector` version - don't worry. You actually have **vector** DB version - we just cutting first symbol (will fix this just to avoid such confusion)

**Comment by aradhya-tiwari** [comment]
yeahh silly mistake! actually was executing commands in turso SQL runner and didn't see the space.
