### ISSUE TITLE
Sqlean version out-of-date in Turso

### ISSUE THREAD

**Issue by dnys1** [tursodatabase/libsql#1599]
My instance currently shows `0.21.8` as the current sqlean version:

```
→  select sqlean_version();
SQLEAN VERSION()
0.21.8
```

I noticed because I ran into this issue (https://github.com/nalgeon/sqlean/issues/109) which was fixed in a later version. For reference, the current sqlean version is `0.24.1` and they seem to have added some cool new functions like `uuid7`.

**Comment by avinassh** [comment]
We are working on this and this will be soon updated :)

**Comment by dnys1** [comment]
Sounds great. Thanks @avinassh

**Comment by avinassh** [comment]
This is updated in the canary image: 

```
$ turso group create <group name> --canary

$ turso create db <db name> --group <group name>

$ turso db shell <db name>

→  select sqlean_version();
SQLEAN VERSION()
0.24.1
```

**Comment by dnys1** [comment]
Awesome, thanks!

**Comment by avinassh** [comment]
The version is now updated in the main image as well (i.e. `canary` flag is not required now)
