### ISSUE TITLE
Creating namespaces in sqld following the docs does not work.

### ISSUE THREAD

**Issue by ptrxyz** [tursodatabase/libsql#1622]
According to https://github.com/tursodatabase/libsql/blob/main/docs/USER_GUIDE.md#multitenancy it should be possible to create namespaces using the simple `curl` command state in the referred doc.
However the call returns 404.

See the following screenshot:
![image](https://github.com/user-attachments/assets/ed69e830-505a-49b7-ad66-ac962a244c45)

In the lower half, sqld is running with `--enable-namespaces` using the officially provided docker image. In the upper half, `curl` command was issued with a response code `404`

**Comment by ubersan** [comment]
I think you need to follow [this guide](https://github.com/tursodatabase/libsql/blob/main/docs/ADMIN_API.md). Essentially namespaces are managed via the admin API, not the users api. So the route you want to access is expected not to be found on this host.

**Comment by avinassh** [comment]
^that is correct. Make sure to set the admin listen address:

```
export SQLD_ADMIN_LISTEN_ADDR="0.0.0.0:8000"
```
