### ISSUE TITLE
missing `libsql-server-v0.24.19/source.tar.gz`

### ISSUE THREAD

**Issue by chenrui333** [tursodatabase/libsql#1675]
👋 looks like `libsql-server-v0.24.19` tag got created, but the artifacts did not get uploaded for them? Thanks!

**Comment by sivukhin** [comment]
Hi @chenrui333!

We are aware of the issue. Will publish new release soon.

**Comment by sivukhin** [comment]
@chenrui333, we fixed our CI and published new release: https://github.com/tursodatabase/libsql/releases/tag/libsql-server-v0.24.20

**Comment by chenrui333** [comment]
thank you!

**Comment by chenrui333** [comment]
https://github.com/Homebrew/homebrew-core/pull/181820

**Comment by chenrui333** [comment]
^^ cc @sivukhin
