### ISSUE TITLE
LibsqlError: SERVER_ERROR: Server returned HTTP status 401

### ISSUE THREAD

**Issue by DaliborPan** [tursodatabase/libsql#1738]
I have a Next.js application using Drizzle ORM and a Turso database. While I can easily connect to the Turso database from localhost, when deployed on Vercel, I encounter the error: LibsqlError: SERVER_ERROR: Server returned HTTP status 401.

- Next.js: 14.2.11
- Drizzle ORM: 0.33.0
- @libsql/client: 0.11.0

I’ve tried everything to fix this: recreating the database, regenerating the auth token, and even hardcoding the database URL and auth token directly into the code (bypassing the use of environment variables). Nothing has worked.

```tsx
// app/login/page.tsx

import { db } from '@/db';

const Page = async () => {
	const users = await db.query.users.findMany();

	console.log('USERS: ', users);

	return ...
}

export default Page;
```

<img width="638" alt="image" src="https://github.com/user-attachments/assets/b692ed00-0d85-4fba-98cd-f23b23fc4a98">

**Comment by ericvalcik** [comment]
Ran into the same issue too, locally everything works but on Vercel I'm getting the same error.

**Comment by DaliborPan** [comment]
Updating @libsql/client: to 0.12.0 solved my issue.

**Comment by DevHustler4** [comment]
Thanks 🙏, I also get the same error,
