### ISSUE TITLE
Bootstrap sync mode

### ISSUE THREAD

**Issue by penberg** [tursodatabase/libsql#427]
Add a mode to libSQL where you provide a sync URL where you boostrap from once, but after that the database becomes an independent SQLite database file, accepting reads and writes.

**Comment by psarna** [comment]
Copying my discord comment:
```
It sounds like syntactic sugar over "create a database with embedded replica, sync it once, close it, and then reopen the synced file as a local database"

We could wrap it in a single pretty function
```
