### ISSUE TITLE
Syncing function does not throw error when providing a non-existant remote database while using the Rust crate

### ISSUE THREAD

**Issue by xinnks** [tursodatabase/libsql#439]
## Reproduce

Use the remote_sync example code on [libsql/crates/core/examples](https://github.com/tursodatabase/libsql/blob/main/crates/core/examples/remote_sync.rs).
Provide all the required variables, making sure the syncUrl is a non-existant database.

## Current behaviour

No error is thrown highlighting this, the syncing seems to run successfully.

## Expected behaviour

Maybe the [sync function](https://github.com/tursodatabase/libsql/blob/main/crates/core/examples/remote_sync.rs#L44) should throw an error?

**Comment by LucioFranco** [comment]
When I connect to an not valid db url that is hosted on the turso platform I get this error 

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ConnectionFailed("status: Unavailable, message: \"grpc-status header missing, mapped from HTTP status code 502\", details: [], metadata: MetadataMap { headers: {\"server\": \"Fly/e440b950 (2023-09-20)\", \"via\": \"1.1 fly.io\", \"fly-request-id\": \"01HBXNJ69F309NJARP33GZ2FQ1-lga\", \"content-length\": \"0\", \"date\": \"Wed, 04 Oct 2023 15:42:23 GMT\"} }")', core/examples/replica.rs:25:29
```

**Comment by LucioFranco** [comment]
https://github.com/chiselstrike/turso/pull/1034 should fix this
