### ISSUE TITLE
README Rust link 404

### ISSUE THREAD

**Issue by peterpeterparker** [tursodatabase/libsql#450]
Hi 👋

Just randomly noticed that the Rust link displayed on the README leads to a 404.

> To get started with the libSQL API:
>
> - JavaScript
> - Rust ------> https://github.com/tursodatabase/libsql/blob/main/core !??!? 

Not sure where is should point to, therefore opened an issue rather than providing a PR, apologies for that.

**Comment by pjhades** [comment]
Noticed the same problem while following the tutorial. Probably https://github.com/libsql/libsql-client-rs, at least the [crate.io page](https://crates.io/crates/libsql-client) points to that repo.

**Comment by MarinPostma** [comment]
Thanks guys for finding this! Let me fix that

**Comment by MarinPostma** [comment]
(for context, we've been moving stuff in the repo this past week, still tying loose ends ;) )
