### ISSUE TITLE
Q: Anything similar to SQLCipher for libsql?

### ISSUE THREAD

**Issue by dougg0k** [tursodatabase/libsql#747]
Is there anything to handle encryption / decryption at rest for libsql?

**Comment by penberg** [comment]
Hey @dougg0k, no SQLCipher for libSQL yet.

**Comment by dougg0k** [comment]
Anything related being worked on?

**Comment by FrancoRATOVOSON** [comment]
Hi! Is encryption / decryption handling near in your roadmap ?

**Comment by penberg** [comment]
Hey @dougg0k and @FrancoRATOVOSON, there is now encryption at rest support as of cd82068edf797d812d1fcc2a4b9ac482fe8cb7ce. We integrated the `sqlite3mc` extension which also supports SQLCipher that I intend to make the default cipher (see #893).
