### ISSUE TITLE
[Rust] Panic when connecting to remote db and syncing embedded replica in Android

### ISSUE THREAD

**Issue by dikatok** [tursodatabase/libsql#789]
Hi, I am using the rust crate in flutter app (android target) using rinf and got panic when trying to open connection to remote db or syncing embedded replica.

<img width="1010" alt="Screenshot 2023-12-14 at 15 58 50" src="https://github.com/tursodatabase/libsql/assets/11844490/483a22b1-3f9b-41eb-a6a7-4e82e918eec0">

Apparently it is caused by the underlying crate https://github.com/rustls/hyper-rustls, which has a documented issue and corresponding fix, https://github.com/rustls/hyper-rustls/issues/187 and https://github.com/rustls/hyper-rustls/pull/228 respectively.

**Comment by LucioFranco** [comment]
Fixed by #792
