### ISSUE TITLE
Rust bindings

### ISSUE THREAD

**Issue by penberg** [tursodatabase/libsql#79]
It would be great to have either a feature flag in the `sqlite` crate https://crates.io/crates/sqlite or a separate `libsql` crate for easy consumption of the library.

**Comment by psarna** [comment]
If migrating to https://crates.io/crates/rusqlite isn't out of the question, it allows consuming a custom sqlite library. It's already used like that in libsql tests: https://github.com/libsql/libsql/blob/fc32062d7b3f3c355fa7ca0d927df355426ac683/Makefile.in#L1329

**Comment by penberg** [comment]
We converged on a `libsql` crate, which is similar to `rusqlite` in API.
