### ISSUE TITLE
Improve compatibility with PostgreSQL dialect

### ISSUE THREAD

**Issue by penberg** [tursodatabase/libsql#80]
The SQL dialect in SQLite/libSQL is very similar to PostgreSQL, but there are some differences, which make porting apps between the two databases hard. For example, PostgreSQL supports dropping multiple tables in a SQL statement, whereas SQLite dialect does not. It would be great if libSQL attempted to narrow the gap between the SQL dialect differences, perhaps as a separate "PostgreSQL compatibility mode" to retain full SQLite compatibility by default. Types are perhaps the most difficult part, but I would just start with sticking to SQLite types.

**Comment by Abdur-rahmaanJ** [comment]
A special mode for postgres sounds awesome!

**Comment by psarna** [comment]
That's also a great umbrella issue! Pretty sure that https://github.com/libsql/libsql/issues/43 would also narrow the gap

**Comment by penberg** [comment]
Here's another issue that's under this umbrella: https://github.com/libsql/libsql/issues/107

**Comment by penberg** [comment]
We no longer are pursuing PostgreSQL compatibility so closing this.
