### ISSUE TITLE
Multiple embedded replicas used in the same directory will erroneously share the metadata file

### ISSUE THREAD

**Issue by psarna** [tursodatabase/libsql#878]
In our current implementation, the metadata file for embedded replicas is named `client_wal_index` and created in the same directory as the local database file:

https://github.com/tursodatabase/libsql/blob/cb2cf1d386b18f350114602527f68f4dd94f8804/libsql/src/replication/remote_client.rs#L29
https://github.com/tursodatabase/libsql/blob/cb2cf1d386b18f350114602527f68f4dd94f8804/libsql/src/replication/local_client.rs#L19
https://github.com/tursodatabase/libsql/blob/cb2cf1d386b18f350114602527f68f4dd94f8804/libsql-replication/src/meta.rs#L63-L64

That's problematic if more than 1 embedded replica is placed in the same directory, and we don't specify anywhere that embedded replicas need to own a unique directory for their own data. And even with just 1 embedded replica, if we decide to replace it with the new one, the new one can erroneously reuse the existing `client_wal_index` file. This is exactly what happens if you run `cargo run --example replica` twice.

We need to try and make the `client_wal_index` file name bound to the database, e.g. by prefixing it with the database name. That wouldn't prevent the second issue of recreating a new replica, but it will at least allow more than 1 embedded replica to share a directory with others.

**Comment by psarna** [comment]
Alternatively, we can specify and document somewhere that an embedded replica must place its local database file in a unique directory that isn't shared with any other replica.

**Comment by MarinPostma** [comment]
that's not gonna be an issue for long, but in the meantime, it would be good to put everything in a directory

**Comment by penberg** [comment]
Fixed by 9dbf604843aa3b24341e55bc5393b8926e55bd68
