### ISSUE TITLE
Broken SQLite API: `PRAGMA index_info` returns `SQL_PARSE_ERROR`

### ISSUE THREAD

**Issue by ishefi** [tursodatabase/libsql#900]
```
alembic 1.13.1
SQLAlchemy 2.0.25
sqlalchemy-libsql 0.1.0
```

I encountered this when trying to run `alembic revision --autogenerate` on my turso instance, it raised the following error:

```
sqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) SQL_PARSE_ERROR: SQL string could not be parsed: unsupported statement: PRAGMA main.index_info(sqlite_autoindex_userhistory_1);
[SQL: PRAGMA main.index_info(sqlite_autoindex_userhistory_1);]
```

I also tried running it directly, the same error was raised:

```python
import sqlalchemy
engine = sqlalchemy.create_engine(...)
with engine.connect() as conn:
    conn.execute(sqlachemy.text("PRAGMA main.index_info('sqlite_autoindex_userhistory_1');"))
```

tried both with and without the `main.` prefix.

This syntax is part of the [SQLite API](https://www.sqlite.org/pragma.html#pragma_index_info) 

The equivalent `SELECT * FROM pragma_index_info('sqlite_autoindex_userhistory_1');` works, but this is not what used by alembic.

**Comment by jedafeza** [comment]
I have the same problem

**Comment by jedafeza** [comment]
![image](https://github.com/tursodatabase/libsql/assets/66031281/8eb15cfe-b92f-4fc5-a39f-9b9c41be160a)

**Comment by penberg** [comment]
@MarinPostma @psarna Is this a limitation in the libSQL server parser?

**Comment by penberg** [comment]
@ishefi @jedafeza This is a bug in the libSQL server parser, pull request #918 ought to fix it.
